apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "123456"
  POSTGRES_USER: "root"
  POSTGRES_DB: "todo"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "123456"
  DB_NAME: "todo"
  DB_HOST: "todo-db"

